// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl-5jrCpi4qfvlwg3iYL4gKjNyySqX1_k',
    appId: '1:13772357179:web:b5ad45801894d7a6e4261e',
    messagingSenderId: '13772357179',
    projectId: 'simple-pizza-app',
    authDomain: 'simple-pizza-app.firebaseapp.com',
    storageBucket: 'simple-pizza-app.appspot.com',
    measurementId: 'G-B536703Z12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsHYT5EdQOC1yaS1MCCYSA3DT9w7Kbp-w',
    appId: '1:13772357179:android:3f1607f2683ceb10e4261e',
    messagingSenderId: '13772357179',
    projectId: 'simple-pizza-app',
    storageBucket: 'simple-pizza-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXdPuE1Y218Utej7sZFwl0zHjRbrobUrk',
    appId: '1:13772357179:ios:d28934d310c618bfe4261e',
    messagingSenderId: '13772357179',
    projectId: 'simple-pizza-app',
    storageBucket: 'simple-pizza-app.appspot.com',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXdPuE1Y218Utej7sZFwl0zHjRbrobUrk',
    appId: '1:13772357179:ios:d28934d310c618bfe4261e',
    messagingSenderId: '13772357179',
    projectId: 'simple-pizza-app',
    storageBucket: 'simple-pizza-app.appspot.com',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl-5jrCpi4qfvlwg3iYL4gKjNyySqX1_k',
    appId: '1:13772357179:web:c60392d1a13c82cde4261e',
    messagingSenderId: '13772357179',
    projectId: 'simple-pizza-app',
    authDomain: 'simple-pizza-app.firebaseapp.com',
    storageBucket: 'simple-pizza-app.appspot.com',
    measurementId: 'G-3922FXB7LY',
  );
}
